// <auto-generated />
using System;
using ApiVending.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiVending.Migrations
{
    [DbContext(typeof(VendingSystemDbContext))]
    partial class VendingSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiVending.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("companies_pkey");

                    b.HasIndex(new[] { "Inn" }, "companies_inn_key")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("files_pkey");

                    b.HasIndex("UploadedBy");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.MachineInventory", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.HasKey("MachineId", "ProductId")
                        .HasName("machine_inventory_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("machine_inventory", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.MachineStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("machine_statuses_pkey");

                    b.HasIndex(new[] { "Name" }, "machine_statuses_name_key")
                        .IsUnique();

                    b.ToTable("machine_statuses", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("MachineId");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_notifications_created");

                    b.HasIndex(new[] { "IsRead" }, "idx_notifications_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_types_pkey");

                    b.HasIndex(new[] { "Name" }, "payment_types_name_key")
                        .IsUnique();

                    b.ToTable("payment_types", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AvgDailySales")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("avg_daily_sales")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("MinStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("min_stock_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sale_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("sales_pkey");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "SaleDate" }, "idx_sales_date");

                    b.HasIndex(new[] { "MachineId" }, "idx_sales_machine");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.ServiceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualCompletionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_completion_date");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<int?>("CounterValueAfter")
                        .HasColumnType("integer")
                        .HasColumnName("counter_value_after");

                    b.Property<int?>("CounterValueBefore")
                        .HasColumnType("integer")
                        .HasColumnName("counter_value_before");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("priority");

                    b.Property<string>("ReportFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("report_file_url");

                    b.Property<string>("ReportText")
                        .HasColumnType("text")
                        .HasColumnName("report_text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Новая'::character varying");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_type");

                    b.Property<int?>("TravelTimeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("travel_time_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("service_tasks_pkey");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("MachineId");

                    b.HasIndex(new[] { "ScheduledDate" }, "idx_tasks_scheduled");

                    b.HasIndex(new[] { "Status" }, "idx_tasks_status");

                    b.ToTable("service_tasks", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("old_status");

                    b.HasKey("Id")
                        .HasName("status_history_pkey");

                    b.HasIndex("ChangedBy");

                    b.ToTable("status_history", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fio");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.VendingMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalibrationIntervalMonths")
                        .HasColumnType("integer")
                        .HasColumnName("calibration_interval_months");

                    b.Property<DateOnly>("CommissioningDate")
                        .HasColumnType("date")
                        .HasColumnName("commissioning_date");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("CurrentCash")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("current_cash")
                        .HasDefaultValueSql("0");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("inventory_number");

                    b.Property<DateOnly?>("LastCalibrationDate")
                        .HasColumnType("date")
                        .HasColumnName("last_calibration_date");

                    b.Property<DateOnly?>("LastInventoryDate")
                        .HasColumnType("date")
                        .HasColumnName("last_inventory_date");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_address");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<DateOnly>("ManufactureDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacture_date");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModemId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modem_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextCalibrationDate")
                        .HasColumnType("date")
                        .HasColumnName("next_calibration_date");

                    b.Property<int?>("OperatingHoursCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("operating_hours_current");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type_id");

                    b.Property<int?>("ResourceHoursTotal")
                        .HasColumnType("integer")
                        .HasColumnName("resource_hours_total");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<int?>("ServiceTimeHours")
                        .HasColumnType("integer")
                        .HasColumnName("service_time_hours");

                    b.Property<int?>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status_id");

                    b.Property<DateOnly?>("SystemEntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("system_entry_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<decimal?>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_revenue")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("vending_machines_pkey");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex(new[] { "CompanyId" }, "idx_machines_company");

                    b.HasIndex(new[] { "StatusId" }, "idx_machines_status");

                    b.HasIndex(new[] { "InventoryNumber" }, "vending_machines_inventory_number_key")
                        .IsUnique();

                    b.HasIndex(new[] { "SerialNumber" }, "vending_machines_serial_number_key")
                        .IsUnique();

                    b.ToTable("vending_machines", (string)null);
                });

            modelBuilder.Entity("ApiVending.Models.File", b =>
                {
                    b.HasOne("ApiVending.Models.User", "UploadedByNavigation")
                        .WithMany("Files")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("files_uploaded_by_fkey");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("ApiVending.Models.MachineInventory", b =>
                {
                    b.HasOne("ApiVending.Models.VendingMachine", "Machine")
                        .WithMany("MachineInventories")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("machine_inventory_machine_id_fkey");

                    b.HasOne("ApiVending.Models.Product", "Product")
                        .WithMany("MachineInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("machine_inventory_product_id_fkey");

                    b.Navigation("Machine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiVending.Models.Notification", b =>
                {
                    b.HasOne("ApiVending.Models.VendingMachine", "Machine")
                        .WithMany("Notifications")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("notifications_machine_id_fkey");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ApiVending.Models.Sale", b =>
                {
                    b.HasOne("ApiVending.Models.VendingMachine", "Machine")
                        .WithMany("Sales")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("sales_machine_id_fkey");

                    b.HasOne("ApiVending.Models.PaymentType", "PaymentType")
                        .WithMany("Sales")
                        .HasForeignKey("PaymentTypeId")
                        .HasConstraintName("sales_payment_type_id_fkey");

                    b.HasOne("ApiVending.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("sales_product_id_fkey");

                    b.Navigation("Machine");

                    b.Navigation("PaymentType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiVending.Models.ServiceTask", b =>
                {
                    b.HasOne("ApiVending.Models.User", "AssignedUser")
                        .WithMany("ServiceTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("service_tasks_assigned_user_id_fkey");

                    b.HasOne("ApiVending.Models.VendingMachine", "Machine")
                        .WithMany("ServiceTasks")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("service_tasks_machine_id_fkey");

                    b.Navigation("AssignedUser");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ApiVending.Models.StatusHistory", b =>
                {
                    b.HasOne("ApiVending.Models.User", "ChangedByNavigation")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("status_history_changed_by_fkey");

                    b.Navigation("ChangedByNavigation");
                });

            modelBuilder.Entity("ApiVending.Models.User", b =>
                {
                    b.HasOne("ApiVending.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_company_id_fkey");

                    b.HasOne("ApiVending.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ApiVending.Models.VendingMachine", b =>
                {
                    b.HasOne("ApiVending.Models.Company", "Company")
                        .WithMany("VendingMachines")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("vending_machines_company_id_fkey");

                    b.HasOne("ApiVending.Models.PaymentType", "PaymentType")
                        .WithMany("VendingMachines")
                        .HasForeignKey("PaymentTypeId")
                        .HasConstraintName("vending_machines_payment_type_id_fkey");

                    b.HasOne("ApiVending.Models.MachineStatus", "Status")
                        .WithMany("VendingMachines")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("vending_machines_status_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("PaymentType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ApiVending.Models.Company", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("VendingMachines");
                });

            modelBuilder.Entity("ApiVending.Models.MachineStatus", b =>
                {
                    b.Navigation("VendingMachines");
                });

            modelBuilder.Entity("ApiVending.Models.PaymentType", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("VendingMachines");
                });

            modelBuilder.Entity("ApiVending.Models.Product", b =>
                {
                    b.Navigation("MachineInventories");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ApiVending.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiVending.Models.User", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("ServiceTasks");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("ApiVending.Models.VendingMachine", b =>
                {
                    b.Navigation("MachineInventories");

                    b.Navigation("Notifications");

                    b.Navigation("Sales");

                    b.Navigation("ServiceTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
